### ISSUE TITLE
There are no threads for gtest

### ISSUE THREAD

**Issue by LewMar** [krux02/minimal_cmake_example#1]
target_link_libraries(unit_tests PUBLIC
    ${GTEST_BOTH_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT}
    example
  )

**Comment by krux02** [comment]
Well this is not supposed to be the perfect setup for gtest, just an example on how to create a cmake project with some test framework. At the moment I am not sure, how much this improves the value of this project as an example.

**Comment by LewMar** [comment]
ok, but I wanted to note that the project does not compile completely.

**Comment by krux02** [comment]
can you elaborate? I just tried it again, and when you made this issue. The tests compile and run and pass on my machine. When the line you wrote is important to make gtest work on another machine that is not mine, it is important that I put it in the example.

**Comment by krux02** [comment]
@LewMar
What platfor are you running?
